FROM golang:1.22-alpine

# On CyberArk dev laptops, golang dependencies are downloaded
# with a corporate proxy in the middle. For these connections to
# succeed we need to configure the proxy CA certificate in the
# build container.
#
# To also allow this script to work on non-CyberArk laptops
# we copy the certificate into the Docker image as a (potentially
# empty) directory, rather than rely on the CA file itself.
ADD build_ca_certificate /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN apk add --no-cache bash && \
    go install github.com/jstemmer/go-junit-report@latest && \
    go install github.com/axw/gocov/gocov@latest && \
    go install github.com/AlekSi/gocov-xml@latest

WORKDIR /cyberark-terraform-provider-secretshub

CMD ./bin/test-entrypoint.sh

EXPOSE 8080
